/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "lcrawler_constants.h"

namespace lcrawler {

const lcrawlerConstants g_lcrawler_constants;

lcrawlerConstants::lcrawlerConstants() {
}

} // namespace

