/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef lcrawler_CONSTANTS_H
#define lcrawler_CONSTANTS_H

#include "lcrawler_types.h"

namespace lcrawler {

class lcrawlerConstants {
 public:
  lcrawlerConstants();

};

extern const lcrawlerConstants g_lcrawler_constants;

} // namespace

#endif
