/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "lspider_constants.h"

namespace lspider {

const lspiderConstants g_lspider_constants;

lspiderConstants::lspiderConstants() {
}

} // namespace

