/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef lspider_CONSTANTS_H
#define lspider_CONSTANTS_H

#include "lspider_types.h"

namespace lspider {

class lspiderConstants {
 public:
  lspiderConstants();

};

extern const lspiderConstants g_lspider_constants;

} // namespace

#endif
